ALTER TABLE "WebhookEvent"
ADD COLUMN "retryCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "replayCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "replayOfId" TEXT,
ADD COLUMN "replayHistory" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN "lastRetryAt" TIMESTAMP(3);
